### PR TITLE
Wrapped js in comment

### LINKED ISSUE #368: Drupal search is indexing js in body
Drupal is indexing script tags inside the Body, which includes all js in the index.php bento file. This is the default behavior for Drupal (it expects js to be limited to the Head). 
The simplest solution is to wrap any js in a comment. This will prevent it from being indexed, but like all js on a page the script itself is exposed and can be viewed in the page source. We will have to address any security implications separately.

### PR DESCRIPTION
**Pull request by StudioZut**
Fixes #368

### CODE REVIEW

**Comment by kerchner** [comment]
Not sure whether this might have collateral impacts.  Initial research indicates caution:  http://www.javascripttoolbox.com/bestpractices/#comments

**Comment by StudioZut** [comment]
I'm looking for a better solution...

**Comment by StudioZut** [comment]
Of course we can insert it into the Drupal theme's Head, as a conditional include for the bento pages. The js itself would live in a file in the bento repo and just need to be deployed whenever changes are made.

**Comment by kerchner** [comment]
Closed as per @StudioZut (replaced by #393)

**Pull request closed without merging**
