### PR TITLE
Fixes #319 - ensures summon handles special characters '+' and '#' correctly

### LINKED ISSUE #319: Key words like C++, C# aren't indexed and returned as expected

### PR DESCRIPTION
**Pull request by adityadharne**
returns correct results for queries that contain certain special characters. eg: 'C/C++' and 'C#'

### CODE REVIEW

**Comment by adityadharne** [comment]
Also ensures summon(articles) does not break if '#' is part of the query.

**Comment by kerchner** [comment]
@adityadharne  This PR has merge conflicts (probably due to the most recent merge into master) - please resolve.  You can do so by re-basing the branch.  Also please add a bit more descriptiveness to the PR title.

**Comment by kerchner** [comment]
@adityadharne This works wonderfully for the articles and books/media results.  However, for the Solr-indexed searches (Databases & Journals) it seems to give the same results as if it ignores the special characters (for example, C++ and C# give the same results as if it ignores the special characters.

This may be the correct result given that the Solr search employs word stemming etc.  Overall it is an improvement since it improves the Summon-based results significantly, and the Solr results are the same (not worse).  But, I wanted to run this by you for your thoughts before merging.

**Comment by adityadharne** [comment]
@kerchner Solr is not indexing the special characters as it should for the search to work. I think we can work on getting Solr to index the special characters in a different ticket maybe.

**Pull request merged**
