### PR TITLE
Fixes #296 - Adds Local/Non-Local IP flag in searches table

### LINKED ISSUE #296: Consider saving whether each search is requested from local/non-local IP address

### PR DESCRIPTION
**Pull request by adityadharne**

### CODE REVIEW

**Comment by kerchner** [comment]
@adityadharne Why are these lines necessary?  
https://github.com/gwu-libraries/obento/blob/0f605064e8fde19900d8b8a70ee2b89336db2dfc/obi/ui/views.py#L589-L590

**Comment by adityadharne** [comment]
@kerchner remnants from debugging; removing them.

**Comment by kerchner** [comment]
These lines would also appear to be unnecessary:
https://github.com/gwu-libraries/obento/blob/49c991daddc5841e00701468fee2645603566c8c/obi/ui/views.py#L749-L751

Also, please clean up PEP8 issues introduced with this PR on lines 589 and 653 (we'll get to the other PEP8 issues in a future PR, but want to avoid adding more)

**Comment by kerchner** [comment]
@adityadharne I believe you'll also need to add the database migration (in https://github.com/gwu-libraries/obento/tree/master/obi/ui/migrations )

**Comment by kerchner** [comment]
@adityadharne let's try this https://github.com/gwu-libraries/obento/blob/8d629aeba37b480e00c236ae4c7c9028254ffbea/obi/ui/models.py#L44 with `blank=True`.  That way, pre-existing Search objects will just have a blank for is_local rather than a False.

**Comment by kerchner** [comment]
@adityadharne why are these lines needed?  https://github.com/gwu-libraries/obento/blob/ae2cbe6920d580f783b199a160f78d47362efddb/obi/ui/views.py#L749-L751

**Pull request merged**
