### PR TITLE
Fixes #148 - Displays the did you mean suggestion

### LINKED ISSUE #148: Did You Mean suggestions / misspelling intelligence
Two different things here:  
* suggestions / autocomplete, 
* "did you mean" spelling corrections

### PR DESCRIPTION
**Pull request by adityadharne**

### CODE REVIEW

**Comment by kerchner** [comment]
- URL in obi/ui/templates/bestbets.html should be a relative address - you probably didn't intend to leave that reference to your server in there.
- In cases where Summon returns a didYouMeanSuggestions with 2 or more elements, do we want to render all of them?  As a point of comparison, how does Summon (or Google, or other search interfaces) present multiple DYM suggestions?

**Comment by adityadharne** [comment]
- Yes I did leave my server reference there unintentionally. I will add a relative address instead.
- Google provides links to all the 'did you mean suggestions' but Summon returns just one 'did you mean suggestion'.

**Comment by kerchner** [comment]
@adityadharne http://gwbento-test.wrlc.org/?q=govrnment works, but http://test.library.gwu.edu/search-all?query=govrnment doesn't display the best bets box in this case.  This is likely because when the CSS currently being applied to the results page on test.library.gwu.edu is applied to the HTML returned by best_bets in this case, it doesn't render the content visibly.

It appears that the CSS being applied might not be in this repository - https://github.com/gwu-libraries/obento/blob/0e1bc8b2ecdcc3b4c4bfb40c65de348802ee7cda/obi/ui/static/css/obento.css doesn't appear to be it.  @StudioZut can you clarify?

**Comment by kerchner** [comment]
@adityadharne (sorry for being away from this for some time).   Did this require any changes to index.php?

**Comment by adityadharne** [comment]
@kerchner It did not require any changes to index.php

**Comment by kerchner** [comment]
...or the script could just get the value of the `dym` tag from within bestbets and set the value of a tag that's already there (under `#form`)

**Comment by kerchner** [comment]
Revised plan as per conversation:
- Add a `<div id="dym">` tag inside home.html and index.php.
- Have the jQuery that's currently inside bestbets.html set the value of the existing `#dym` tag to `response.dym`.

**Comment by adityadharne** [comment]
We can even avoid displaying the suggestions by using best bets totally. Creating a separate view for the did you mean suggestions and utilizing the same response object that contains results for best bets or Articles will clean it up. It will also avoid a potential style sheet conflict.

**Comment by kerchner** [comment]
As per discussion, we'll merge this and have carved off a new ticket (#379) for a more elegant implementation of this feature.

**Pull request merged**
